pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - approved-reviews-by=@fedora-infra/fedora-messaging-maintainers
  - status-success=continuous-integration/travis-ci/pr
  - status-success=DCO
  name: default
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - author=@fedora-infra/fedora-messaging-maintainers
  - '#approved-reviews-by>=1'
  - status-success=continuous-integration/travis-ci/pr
  - status-success=DCO
  name: default-from-fedora-messaging-team
